# Numpy v1.13
# Content:
1. Numpy vs Regular python
2. How to create a numpy 1D array?
3. How to create a numpy 2D array?
4. How to create a string 1D array ?
5. Create a String and int in 1D array
6. Create a float and int in 1D array (upcasting)
7. Create a float and int in 1D array (upcasting with int)
8. Saving numpy array into a file
9. Loading a numpy array from a file

### How to generate numpy array from nothing?
10. Generate 2D zeros Array
11. Generate 2D ones Array
12. Generate array with full function
13. Generate Identity matrix
14. Generate diagonal matrix
15. Generate 1D array using arrange function
16. Generate 1D aaray by using linspace function
17. How to reshape an aranged 1D array to 2D array?
18. How to reshape linspace 1D array to 2D array?
19. Create random array
20. Create a 1000 x 1000 ndarray of random floats drawn from normal (Gaussian) distribution

##### *Question: create a 4 x 4 ndarray that only contains consecutive even numbers from 2 to 32 (inclusive)
21. Accessing, Deleting, and Inserting Elements Into ndarrays
22. How to delete element from array?
23. How to append an element to array?
24. How to insert element to an array?
25. How to stack an array to another vertical and horizontal?
26. Slicing ndarrays
27. Slicing important feature
28. Using copy function with slicing
29. Using 1D array as indices for slicing
30. Using diag function to get the diagonal elements
31. Using unique function with array

### Boolean Indexing, Set Operations, and Sorting
32. Boolean indexing
33. Set operations and comparing two arrays
34. Sorting using sort function
35. Keeping only unique elements after sorting
36. Sorting using sort method
37. Sorting 2D array by columns and rows

### Arithmetic operations and Broadcasting
38. Arithmetic operations
39. Arithmetic operations on 2D arrays
40. Using sqrt, exp, power functions
41. Using mean, sum, min, max, standard deviation, median
42. Add single numbers to all the elements of 2D array
43. Broadcasting


# 1. Numpy vs Regular python

In [1]:
import numpy as np
import time

In [2]:
x=np.random.random(10000000)

In [3]:
start_time=time.time()
mean_py=sum(x)/len(x)
execute_time=time.time()-start_time
print(execute_time)

0.6821761131286621


In [4]:
start_time=time.time()
mean_numpy=np.mean(x)
execute_time=time.time()-start_time
print(execute_time)

0.012978792190551758


# 2. How to create a numpy 1D array?

In [5]:
# We create a 1D ndarray that contains only integers
x = np.array([1, 2, 3, 4, 5])
# Let's print the ndarray we just created using the print() command
print('x = ', x)
print(type(x))
print('The elements in x are of type:', x.dtype)
print('x has dimensions:', x.shape)

x =  [1 2 3 4 5]
<class 'numpy.ndarray'>
The elements in x are of type: int32
x has dimensions: (5,)


# 3. How to create a numpy 2D array?

In [6]:
# We create a rank 2 ndarray that only contains integers
Y = np.array([[1,2,3],[4,5,6],[7,8,9], [10,11,12]])

# We print Y
print('Y = \n', Y, '\n')

# We print information about Y
print('Y has dimensions:', Y.shape)
print('Y has a total of', Y.size, 'elements')
print('Y is an object of type:', type(Y))
print('The elements in Y are of type:', Y.dtype)

Y = 
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]] 

Y has dimensions: (4, 3)
Y has a total of 12 elements
Y is an object of type: <class 'numpy.ndarray'>
The elements in Y are of type: int32


# 4. How to create a string 1D array?

In [7]:
# We create a rank 1 ndarray that only contains strings
x = np.array(['Hello', 'World'])

# We print x
print('x = ', x)
# We print information about x
print('x has dimensions:', x.shape)
print('x is an object of type:', type(x))
print('The elements in x are of type:', x.dtype)

x =  ['Hello' 'World']
x has dimensions: (2,)
x is an object of type: <class 'numpy.ndarray'>
The elements in x are of type: <U5


#### to read more abut numpy data type you can use this link :
https://docs.scipy.org/doc/numpy-1.13.0/user/basics.types.html

# 5. Create a String and int in 1D array

In [8]:
# We create a rank 1 ndarray from a Python list that contains integers and strings
x = np.array([1, 2, 'World'])

# We print the ndarray
print('x = ', x)
print("\n")

# We print information about x
print('x has dimensions:', x.shape)
print('x is an object of type:', type(x))
print('The elements in x are of type:', x.dtype)

x =  ['1' '2' 'World']


x has dimensions: (3,)
x is an object of type: <class 'numpy.ndarray'>
The elements in x are of type: <U11


# 6. Create a float and int in 1D array (upcasting)

In [9]:
# We create a rank 1 ndarray that contains integers
x = np.array([1,2,3])

# We create a rank 1 ndarray that contains floats
y = np.array([1.0,2.0,3.0])

# We create a rank 1 ndarray that contains integers and floats
z = np.array([1, 2.5, 4])

# We print the dtype of each ndarray
print('The elements in x are of type:', x.dtype)
print('The elements in y are of type:', y.dtype)
print('The elements in z are of type:', z.dtype)

The elements in x are of type: int32
The elements in y are of type: float64
The elements in z are of type: float64


# 7. Create a float and int in 1D array (upcasting with int)

In [10]:
# We create a rank 1 ndarray of floats but set the dtype to int64
x = np.array([1.5, 2.2, 3.7, 4.0, 5.9], dtype = np.int32)

# We print x
print('x = ', x)
print()

# We print the dtype x
print('The elements in x are of type:', x.dtype)

x =  [1 2 3 4 5]

The elements in x are of type: int32


# 8. Saving numpy array into a file

In [11]:
# We create a rank 1 ndarray
x = np.array([1, 2, 3, 4, 5])

# We save x into the current directory as 
np.save('my_array', x)

# 9. Loading a numpy array from a file

In [12]:
# We load the saved array from our current directory into variable y
y = np.load('my_array.npy')

# We print y
print('y = ', y)
print("\n")

# We print information about the ndarray we loaded
print('y is an object of type:', type(y))
print('The elements in y are of type:', y.dtype)

y =  [1 2 3 4 5]


y is an object of type: <class 'numpy.ndarray'>
The elements in y are of type: int32


# How to generate numpy array from nothing ?

# 10. Generate 2D zeros Array

In [13]:
# We create a 3 x 4 ndarray full of zeros. 
X = np.zeros((3,4))

# We print X
print('X =\n', X)
print("\n")

# We print information about X
print('X has dimensions:', X.shape)
print('X is an object of type:', type(X))
print('The elements in X are of type:', X.dtype)

X =
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


X has dimensions: (3, 4)
X is an object of type: <class 'numpy.ndarray'>
The elements in X are of type: float64


# 11. Generate 2D ones Array

In [14]:
# We create a 3 x 2 ndarray full of ones. 
X = np.ones((3,2))

# We print X

print('X = \n', X)
print("\n")

# We print information about X
print('X has dimensions:', X.shape)
print('X is an object of type:', type(X))
print('The elements in X are of type:', X.dtype)

X = 
 [[1. 1.]
 [1. 1.]
 [1. 1.]]


X has dimensions: (3, 2)
X is an object of type: <class 'numpy.ndarray'>
The elements in X are of type: float64


# 12. Generate array with full function

In [15]:
# We create a 2 x 3 ndarray full of fives. 
X = np.full((2,3), 5.0) 

# We print X
print('X = \n', X)
print('\n')

# We print information about X
print('X has dimensions:', X.shape)
print('X is an object of type:', type(X))
print('The elements in X are of type:', X.dtype)

X = 
 [[5. 5. 5.]
 [5. 5. 5.]]


X has dimensions: (2, 3)
X is an object of type: <class 'numpy.ndarray'>
The elements in X are of type: float64


# 13. Generate Identity matrix

In [16]:
# We create a 5 x 5 Identity matrix. 
X = np.eye(5)

# We print X
print('X = \n', X)
print('\n')

# We print information about X
print('X has dimensions:', X.shape)
print('X is an object of type:', type(X))
print('The elements in X are of type:', X.dtype) 

X = 
 [[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


X has dimensions: (5, 5)
X is an object of type: <class 'numpy.ndarray'>
The elements in X are of type: float64


# 14. Generate diagonal matrix

In [17]:
# Create a 4 x 4 diagonal matrix that contains the numbers 10,20,30, and 50
# on its main diagonal
X = np.diag([10,20,30,50])

# We print X
print('X = \n', X)

X = 
 [[10  0  0  0]
 [ 0 20  0  0]
 [ 0  0 30  0]
 [ 0  0  0 50]]


# 15. Generate 1D array using arrange function

In [18]:
# We create a rank 1 ndarray that has sequential integers from 0 to 9
x = np.arange(10)

# We print the ndarray
print('x = ', x)
print('\n')

# We print information about the ndarray
print('x has dimensions:', x.shape)
print('x is an object of type:', type(x))
print('The elements in x are of type:', x.dtype)

x =  [0 1 2 3 4 5 6 7 8 9]


x has dimensions: (10,)
x is an object of type: <class 'numpy.ndarray'>
The elements in x are of type: int32


In [19]:
# We create a rank 1 ndarray that has sequential integers from 4 to 9. 
x = np.arange(4,10)

# We print the ndarray
print('x = ', x)
print('\n')

# We print information about the ndarray
print('x has dimensions:', x.shape)
print('x is an object of type:', type(x))
print('The elements in x are of type:', x.dtype)

x =  [4 5 6 7 8 9]


x has dimensions: (6,)
x is an object of type: <class 'numpy.ndarray'>
The elements in x are of type: int32


In [20]:
# We create a rank 1 ndarray that has evenly spaced integers from 1 to 13 in steps of 3.
x = np.arange(1,14,3)

# We print the ndarray
print('x = ', x)
print('\n')

# We print information about the ndarray
print('x has dimensions:', x.shape)
print('x is an object of type:', type(x))
print('The elements in x are of type:', x.dtype)

x =  [ 1  4  7 10 13]


x has dimensions: (5,)
x is an object of type: <class 'numpy.ndarray'>
The elements in x are of type: int32


In [21]:
# We create a rank 1 ndarray that has evenly spaced integers from 1 to 13 in steps of 0.3.
x = np.arange(1,14,0.3)

# We print the ndarray
print('x = ', x)
print('\n')

# We print information about the ndarray
print('x has dimensions:', x.shape)
print('x is an object of type:', type(x))
print('The elements in x are of type:', x.dtype)

x =  [ 1.   1.3  1.6  1.9  2.2  2.5  2.8  3.1  3.4  3.7  4.   4.3  4.6  4.9
  5.2  5.5  5.8  6.1  6.4  6.7  7.   7.3  7.6  7.9  8.2  8.5  8.8  9.1
  9.4  9.7 10.  10.3 10.6 10.9 11.2 11.5 11.8 12.1 12.4 12.7 13.  13.3
 13.6 13.9]


x has dimensions: (44,)
x is an object of type: <class 'numpy.ndarray'>
The elements in x are of type: float64


# 16. Generate 1D aaray by using linspace function

In [22]:
import numpy as np
x=np.linspace(0,25,10)
# step= (sotp-start)/(N-1)
# step= (25-0)/(10-1)

print('x = \n', x)
print('\n')

# We print information about the ndarray
print('x has dimensions:', x.shape)
print('x is an object of type:', type(x))
print('The elements in x are of type:', x.dtype) 

x = 
 [ 0.          2.77777778  5.55555556  8.33333333 11.11111111 13.88888889
 16.66666667 19.44444444 22.22222222 25.        ]


x has dimensions: (10,)
x is an object of type: <class 'numpy.ndarray'>
The elements in x are of type: float64


In [23]:
x=np.linspace(5,63,10,endpoint=False)
# step=(stop-start)/N
# step=(63-5)/10
print('x = ', x)
print('\n')

# We print information about the ndarray
print('x has dimensions:', x.shape)
print('x is an object of type:', type(x))
print('The elements in x are of type:', x.dtype)

x =  [ 5.  10.8 16.6 22.4 28.2 34.  39.8 45.6 51.4 57.2]


x has dimensions: (10,)
x is an object of type: <class 'numpy.ndarray'>
The elements in x are of type: float64


# 17. How to reshape an aranged 1D array to 2D array?

In [24]:
# We create a rank 1 ndarray with sequential integers from 0 to 19
x = np.arange(20)

# We print x
print('Original x = ', x)

# We reshape x into a 4 x 5 ndarray 
x = np.reshape(x, (4,5))

# We print the reshaped x
print('Reshaped x = \n', x)
print('\n')

# We print information about the reshaped x
print('x has dimensions:', x.shape)
print('x is an object of type:', type(x))
print('The elements in x are of type:', x.dtype)

Original x =  [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
Reshaped x = 
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


x has dimensions: (4, 5)
x is an object of type: <class 'numpy.ndarray'>
The elements in x are of type: int32


In [25]:
# We create a a rank 1 ndarray with sequential integers from 0 to 19 and
# reshape it to a 4 x 5 array 
Y = np.arange(20).reshape(4, 5)

# We print Y
print('Y = \n', Y)
print()

# We print information about Y
print('Y has dimensions:', Y.shape)
print('Y is an object of type:', type(Y))
print('The elements in Y are of type:', Y.dtype) 

Y = 
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]

Y has dimensions: (4, 5)
Y is an object of type: <class 'numpy.ndarray'>
The elements in Y are of type: int32


# 18. How to reshape linspace 1D array to 2D array?

In [26]:
# We create a rank 1 ndarray with 10 integers evenly spaced between 0 and 50,
# with 50 excluded. We then reshape it to a 5 x 2 ndarray
X = np.linspace(0,50,10, endpoint=False).reshape(5,2)

# We print X
print('X = \n', X)
print('\n')

# We print information about X
print('X has dimensions:', X.shape)
print('X is an object of type:', type(X))
print('The elements in X are of type:', X.dtype)

X = 
 [[ 0.  5.]
 [10. 15.]
 [20. 25.]
 [30. 35.]
 [40. 45.]]


X has dimensions: (5, 2)
X is an object of type: <class 'numpy.ndarray'>
The elements in X are of type: float64


# 19. Create random array

In [27]:
# We create a 3 x 3 ndarray with random floats in the half-open interval [0.0, 1.0).
X = np.random.random(size=(3,3))

# We print X
print('X = \n', X)
print('\n')

# We print information about X
print('X has dimensions:', X.shape)
print('X is an object of type:', type(X))
print('The elements in x are of type:', X.dtype)

X = 
 [[0.64923802 0.66933975 0.03602322]
 [0.71544002 0.87214176 0.86414931]
 [0.48634448 0.28742625 0.02212149]]


X has dimensions: (3, 3)
X is an object of type: <class 'numpy.ndarray'>
The elements in x are of type: float64


In [28]:
# We create a 3 x 2 ndarray with random integers in the half-open interval [4, 15).
X = np.random.randint(4,15,size=(3,2))

# We print X
print('X = \n', X)
print()

# We print information about X
print('X has dimensions:', X.shape)
print('X is an object of type:', type(X))
print('The elements in X are of type:', X.dtype)

X = 
 [[ 8  6]
 [ 6  7]
 [ 4 11]]

X has dimensions: (3, 2)
X is an object of type: <class 'numpy.ndarray'>
The elements in X are of type: int32


# 20. Create a 1000 x 1000 ndarray of random floats drawn from normal (Gaussian) distribution

In [29]:
# We create a 1000 x 1000 ndarray of random floats drawn from normal (Gaussian) distribution
# with a mean of zero and a standard deviation of 0.1.
X = np.random.normal(0, 0.1, size=(1000,1000))

# We print X
print('X = \n', X)
print()

# We print information about X
print('X has dimensions:', X.shape)
print('X is an object of type:', type(X))
print('The elements in X are of type:', X.dtype)
print('The elements in X have a mean of:', X.mean())
print('The elements in X have a standard deviation of:', X.std())
print('The maximum value in X is:', X.max())
print('The minimum value in X is:', X.min())
print('X has', (X < 0).sum(), 'negative numbers')
print('X has', (X > 0).sum(), 'positive numbers')

X = 
 [[-0.09396566  0.1704717  -0.04626514 ... -0.12529374 -0.05831258
  -0.01368449]
 [ 0.07335178  0.13342019 -0.05966785 ... -0.05068656  0.01983392
  -0.18358948]
 [ 0.08081038  0.13781753 -0.0674166  ...  0.09738576  0.08615808
   0.0916551 ]
 ...
 [ 0.06205081 -0.12895172  0.05545044 ... -0.09017081 -0.05843139
  -0.16056248]
 [ 0.07067731  0.02672932 -0.02459902 ... -0.05052943 -0.06812226
   0.08689212]
 [ 0.14696478 -0.00940339  0.07750493 ... -0.05433355 -0.04611708
  -0.05523696]]

X has dimensions: (1000, 1000)
X is an object of type: <class 'numpy.ndarray'>
The elements in X are of type: float64
The elements in X have a mean of: -6.0853315118227236e-05
The elements in X have a standard deviation of: 0.10001187203478032
The maximum value in X is: 0.5024956300384794
The minimum value in X is: -0.5010981446760988
X has 499877 negative numbers
X has 500123 positive numbers


### Question: create a 4 x 4 ndarray that only contains consecutive even numbers from 2 to 32 (inclusive)

In [30]:
#X=np.arange(2,34,2).reshape(4,4)
X=np.linspace(2,32,16).reshape(4,4)
X

array([[ 2.,  4.,  6.,  8.],
       [10., 12., 14., 16.],
       [18., 20., 22., 24.],
       [26., 28., 30., 32.]])

# 21. Accessing, Deleting, and Inserting Elements Into ndarrays

In [31]:
# We create a rank 1 ndarray that contains integers from 1 to 5
x = np.array([1, 2, 3, 4, 5])

# We print x
print('x = ', x)
print()

# Let's access some elements with positive indices
print('This is First Element in x:', x[0]) 
print('This is Second Element in x:', x[1])
print('This is Fifth (Last) Element in x:', x[4])
print()

# Let's access the same elements with negative indices
print('This is First Element in x:', x[-5])
print('This is Second Element in x:', x[-4])
print('This is Fifth (Last) Element in x:', x[-1])

x =  [1 2 3 4 5]

This is First Element in x: 1
This is Second Element in x: 2
This is Fifth (Last) Element in x: 5

This is First Element in x: 1
This is Second Element in x: 2
This is Fifth (Last) Element in x: 5


In [32]:
# We create a rank 1 ndarray that contains integers from 1 to 5
x = np.array([1, 2, 3, 4, 5])

# We print the original x
print('Original:\n x = ', x)

# We change the fourth element in x from 4 to 20
x[3] = 20

# We print x after it was modified 
print('Modified:\n x = ', x)

Original:
 x =  [1 2 3 4 5]
Modified:
 x =  [ 1  2  3 20  5]


In [33]:
# We create a 3 x 3 rank 2 ndarray that contains integers from 1 to 9
X = np.array([[1,2,3],[4,5,6],[7,8,9]])

# We print X
print('X = \n', X)
print()

# Let's access some elements in X
print('This is (0,0) Element in X:', X[0,0])
print('This is (0,1) Element in X:', X[0,1])
print('This is (2,2) Element in X:', X[2,2])
print('This is (2,1) Element in X:', X[2][1])

X = 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

This is (0,0) Element in X: 1
This is (0,1) Element in X: 2
This is (2,2) Element in X: 9
This is (2,1) Element in X: 8


In [34]:
# We create a 3 x 3 rank 2 ndarray that contains integers from 1 to 9
X = np.array([[1,2,3],[4,5,6],[7,8,9]])

# We print the original x
print('Original X = \n', X)
print()

# We change the (0,0) element in X from 1 to 20
X[0,0] = 20

# We print X after it was modified 
print('Modified X = \n', X)

Original X = 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

Modified X = 
 [[20  2  3]
 [ 4  5  6]
 [ 7  8  9]]


# 22. How to delete element from array?

### How to delete an element in a 1D array:

In [35]:
# np.delete(ndarray, elements, axis)

# We create a rank 1 ndarray 
x = np.array([1, 2, 3, 4, 5])

# We print x
print('Original x = ', x)

# We delete the first and last element of x
x = np.delete(x, [0,4])

# We print x with the first and last element deleted
print()
print('Modified x = ', x)

Original x =  [1 2 3 4 5]

Modified x =  [2 3 4]


### How to delete a row or a column in a 2D array:

In [36]:
# We create a rank 2 ndarray
Y = np.array([[1,2,3],[4,5,6],[7,8,9]])

# We print Y
print('Original Y = \n', Y)

# We delete the first row of y
w = np.delete(Y, 0, axis=0)

# We delete the first and last column of y
v = np.delete(Y, [0,2], axis=1)

# We print w
print()
print('w = \n', w)

# We print v
print()
print('v = \n', v)

Original Y = 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

w = 
 [[4 5 6]
 [7 8 9]]

v = 
 [[2]
 [5]
 [8]]


# 23. How to append an element to array?

### How to append an element to a 1D array:

In [37]:
# np.append(ndarray, elements, axis)

# We create a rank 1 ndarray 
x = np.array([1, 2, 3, 4, 5])

# We print x
print('Original x = ', x)
print()

# We append the integer 6 to x
x=np.append(x, 6)

# We print x
print('x = ', x)
print()

# We append the integer 7 and 8 to x
x = np.append(x, [7,8])

# We print x
print('x = ', x)
print()

Original x =  [1 2 3 4 5]

x =  [1 2 3 4 5 6]

x =  [1 2 3 4 5 6 7 8]



### How to append a row or a column in a 2D array:

In [38]:
# We create a rank 2 ndarray 
Y = np.array([[1,2,3],[4,5,6]])

# We print Y
print('Original Y = \n', Y)
print()

# We append a new row containing 7,8,9 to y
v = np.append(Y, [[7,8,9]], axis=0)

# We append a new column containing 9 and 10 to y
q = np.append(Y,[[9],[10]], axis=1)

# We print v
print('v = \n', v)
print()

# We print q
print('q = \n', q)

Original Y = 
 [[1 2 3]
 [4 5 6]]

v = 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

q = 
 [[ 1  2  3  9]
 [ 4  5  6 10]]


# 24. How to insert element to an array?

### How to insert an element to a 1D array:

In [39]:
#np.insert(ndarray, index, elements, axis)
# We create a rank 1 ndarray 
x = np.array([1, 2, 5, 6, 7])

# We print x
print('Original x = ', x)

# We insert the integer 3 and 4 between 2 and 5 in x. 
x = np.insert(x,2,[3,4])

# We print x with the inserted elements
print()
print('x = ', x)

Original x =  [1 2 5 6 7]

x =  [1 2 3 4 5 6 7]


### How to insert a row or a column in a 2D array:

In [40]:
# We create a rank 2 ndarray 
Y = np.array([[1,2,3],[7,8,9]])

# We print Y
print('Original Y = \n', Y)

# We insert a row between the first and last row of y
w = np.insert(Y,1,[4,5,6],axis=0)

# We insert a column full of 5s between the first and second column of y
v = np.insert(Y,1,[5,10], axis=1)

# We print w
print()
print('w = \n', w)

# We print v
print()
print('v = \n', v)

Original Y = 
 [[1 2 3]
 [7 8 9]]

w = 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

v = 
 [[ 1  5  2  3]
 [ 7 10  8  9]]


# 25. How to stack an array to another vertical and horizontal?

In [41]:
# We create a rank 1 ndarray 
x = np.array([1,2])

# We create a rank 2 ndarray 
Y = np.array([[3,4],[5,6]])

# We print x
print('x = ', x)
print()

# We print Y
print('Y = \n', Y)
print()

# We stack x on top of Y
z = np.vstack((x,Y))

# We stack x on the right of Y. We need to reshape x in order to stack it on the right of Y. 
w = np.hstack((Y,x.reshape(2,1)))

# We print z
print('z = \n', z)
print()

# We print w
print('w = \n', w)

x =  [1 2]

Y = 
 [[3 4]
 [5 6]]

z = 
 [[1 2]
 [3 4]
 [5 6]]

w = 
 [[3 4 1]
 [5 6 2]]


In [42]:
x.reshape(2,1)

array([[1],
       [2]])

# 26. Slicing ndarrays

In [43]:
# We create a 4 x 5 ndarray that contains integers from 0 to 19
X = np.arange(20).reshape(4, 5)

# We print X
print('X = \n', X)
print()

# We select all the elements that are in the 2nd through 4th rows and in the 3rd to 5th columns
Z = X[1:4,2:5]

# We print Z
print('Z = \n', Z)
print()

# We can select the same elements as above using method 2
W = X[1:,2:5]

# We print W
print('W = \n', W)
print()

# We select all the elements that are in the 1st through 3rd rows and in the 3rd to 4th columns
Y = X[:3,2:5]

# We print Y
print('Y = \n', Y)
print()

# We select all the elements in the 3rd row
v = X[2,:]

# We print v
print('v = ', v)
print()

# We select all the elements in the 3rd column
q = X[:,2]

# We print q
print('q = ', q)
print("q shape=",q.shape)
print()

# We select all the elements in the 3rd column but return a rank 2 ndarray
R = X[:,2:3]

# We print R
print('R = \n', R)
print("R shape=",R.shape)

X = 
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]

Z = 
 [[ 7  8  9]
 [12 13 14]
 [17 18 19]]

W = 
 [[ 7  8  9]
 [12 13 14]
 [17 18 19]]

Y = 
 [[ 2  3  4]
 [ 7  8  9]
 [12 13 14]]

v =  [10 11 12 13 14]

q =  [ 2  7 12 17]
q shape= (4,)

R = 
 [[ 2]
 [ 7]
 [12]
 [17]]
R shape= (4, 1)


# 27. Slicing important feature

In [44]:
# We create a 4 x 5 ndarray that contains integers from 0 to 19
X = np.arange(20).reshape(4, 5)

# We print X
print('X = \n', X)
print()

# We select all the elements that are in the 2nd through 4th rows and in the 3rd to 4th columns
Z = X[1:4,2:5]

# We print Z
print('Z = \n', Z)
print()

# We change the last element in Z to 555
Z[2,2] = 555

# We print Z
print('Z = \n', Z)
print()

# We print X
print('X = \n', X)
print()

X = 
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]

Z = 
 [[ 7  8  9]
 [12 13 14]
 [17 18 19]]

Z = 
 [[  7   8   9]
 [ 12  13  14]
 [ 17  18 555]]

X = 
 [[  0   1   2   3   4]
 [  5   6   7   8   9]
 [ 10  11  12  13  14]
 [ 15  16  17  18 555]]



# 28. Using copy function with slicing

In [45]:
# We create a 4 x 5 ndarray that contains integers from 0 to 19
X = np.arange(20).reshape(4, 5)

# We print X
print('X = \n', X)
print()

# create a copy of the slice using the np.copy() function
Z = np.copy(X[1:4,2:5])

#  create a copy of the slice using the copy as a method
W = X[1:4,2:5].copy()

# We change the last element in Z to 555
Z[2,2] = 555

# We change the last element in W to 444
W[2,2] = 444

# We print X
print('X = \n', X)
print()

# We print Z
print('Z = \n', Z)
print()

# We print W
print('W = \n', W)

X = 
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]

X = 
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]

Z = 
 [[  7   8   9]
 [ 12  13  14]
 [ 17  18 555]]

W = 
 [[  7   8   9]
 [ 12  13  14]
 [ 17  18 444]]


# 29. Using 1D array as indices for slicing

In [46]:
# We create a 4 x 5 ndarray that contains integers from 0 to 19
X = np.arange(20).reshape(4, 5)

# We create a rank 1 ndarray that will serve as indices to select elements from X
indices = np.array([1,3])

# We print X
print('X = \n', X)
print()

# We print indices
print('indices = ', indices)
print()

# We use the indices ndarray to select the 2nd and 4th row of X
Y = X[indices,:]

# We use the indices ndarray to select the 2nd and 4th column of X
Z = X[:, indices]

# We print Y
print('Y = \n', Y)
print()

# We print Z
print('Z = \n', Z)

X = 
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]

indices =  [1 3]

Y = 
 [[ 5  6  7  8  9]
 [15 16 17 18 19]]

Z = 
 [[ 1  3]
 [ 6  8]
 [11 13]
 [16 18]]


# 30. Using diag function to get the diagonal elements

In [47]:
# np.diag(ndarray, k=N)

# We create a 4 x 5 ndarray that contains integers from 0 to 19
X = np.arange(25).reshape(5, 5)

# We print X
print('X = \n', X)
print()

# We print the elements in the main diagonal of X
print('z =', np.diag(X))
print()

# We print the elements above the main diagonal of X
print('y =', np.diag(X, k=1))
print()

# We print the elements below the main diagonal of X
print('w = ', np.diag(X, k=-1))

X = 
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]

z = [ 0  6 12 18 24]

y = [ 1  7 13 19]

w =  [ 5 11 17 23]


# 31. Using unique function with array

In [48]:
# np.unique(ndarray)

# Create 3 x 3 ndarray with repeated values
X = np.array([[9,2,3],[5,150,8],[1,2,3]])

# We print X
print('X = \n', X)
print()

# We print the unique elements of X 
print('The unique elements in X are:',np.unique(X))

X = 
 [[  9   2   3]
 [  5 150   8]
 [  1   2   3]]

The unique elements in X are: [  1   2   3   5   8   9 150]


# Boolean Indexing, Set Operations, and Sorting

# 32. Boolean indexing

In [49]:
# We create a 5 x 5 ndarray that contains integers from 0 to 24
X = np.arange(25).reshape(5, 5)

# We print X
print('Original X = \n', X)
print()

# We use Boolean indexing to select elements in X:
print('The elements in X that are greater than 10:', X[X > 10])
print('The elements in X that less than or equal to 7:', X[X <= 7])
print('The elements in X that are between 10 and 17:', X[(X > 10) & (X < 17)])
print()

# We use Boolean indexing to assign the elements that are between 10 and 17 the value of -1
X[(X > 10) & (X < 17)] = -1

# We print X
print('X = \n', X)

Original X = 
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]

The elements in X that are greater than 10: [11 12 13 14 15 16 17 18 19 20 21 22 23 24]
The elements in X that less than or equal to 7: [0 1 2 3 4 5 6 7]
The elements in X that are between 10 and 17: [11 12 13 14 15 16]

X = 
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 -1 -1 -1 -1]
 [-1 -1 17 18 19]
 [20 21 22 23 24]]


# 33. Set operations and comparing two arrays

In [50]:
# We create a rank 1 ndarray
x = np.array([1,2,3,4,5])

# We create a rank 1 ndarray
y = np.array([6,7,2,8,4])

# We print x
print('x = ', x)
print()

# We print y
print('y = ', y)
print()

# We use set operations to compare x and y:
print('The elements that are both in x and y:', np.intersect1d(x,y))
print('The elements that are in x that are not in y:', np.setdiff1d(x,y))
print('The elements that are in y that are not in x:', np.setdiff1d(y,x))
print('All the elements of x and y:',np.union1d(x,y))

x =  [1 2 3 4 5]

y =  [6 7 2 8 4]

The elements that are both in x and y: [2 4]
The elements that are in x that are not in y: [1 3 5]
The elements that are in y that are not in x: [6 7 8]
All the elements of x and y: [1 2 3 4 5 6 7 8]


# 34. Sorting using sort function

In [51]:
# We create an unsorted rank 1 ndarray
x = np.random.randint(1,12,size=(10,))

# We print x
print('Original x = \t\t\t', x)
print()

# We sort x and print the sorted array using sort as a function.
print('Sorted x (out of place):\t', np.sort(x))
print()

# When we sort out of place the original array remains intact. To see this we print x again
print('x after sorting:\t\t', x)

Original x = 			 [ 8  3 10  2 10  9 10  2  5  3]

Sorted x (out of place):	 [ 2  2  3  3  5  8  9 10 10 10]

x after sorting:		 [ 8  3 10  2 10  9 10  2  5  3]


# 35. Keeping only unique elements after sorting

In [52]:
print('Original x = ', x)
print()

# We sort x but only keep the unique elements in x
print("Sorted unique elements of X=", np.sort(np.unique(x)))

Original x =  [ 8  3 10  2 10  9 10  2  5  3]

Sorted unique elements of X= [ 2  3  5  8  9 10]


# 36. Sorting using sort method

In [53]:
# We create an unsorted rank 1 ndarray
x = np.random.randint(1,11,size=(10,))

# We print x
print('Original x = ', x)
print()

# We sort x and print the sorted array using sort as a method.
x.sort()

# When we sort in place the original array is changed to the sorted array. To see this we print x again
print('x after sorting:', x)

Original x =  [ 7  5  6  6  7  2  7 10  9 10]

x after sorting: [ 2  5  6  6  7  7  7  9 10 10]


# 37. Sorting 2D array by columns and rows

In [54]:
# We create an unsorted rank 2 ndarray
X = np.random.randint(1,11,size=(5,5))

# We print X
print('Original X = \n', X)
print()

# We sort the columns of X and print the sorted array
print('X with sorted columns :\n', np.sort(X, axis = 0))
print()

# We sort the rows of X and print the sorted array
print('X with sorted rows :\n', np.sort(X, axis = 1))

Original X = 
 [[10  6  5 10  2]
 [ 2  7  2 10  2]
 [ 8  8  9 10  2]
 [ 9 10  5  8  4]
 [ 4  1  6  1  2]]

X with sorted columns :
 [[ 2  1  2  1  2]
 [ 4  6  5  8  2]
 [ 8  7  5 10  2]
 [ 9  8  6 10  2]
 [10 10  9 10  4]]

X with sorted rows :
 [[ 2  5  6 10 10]
 [ 2  2  2  7 10]
 [ 2  8  8  9 10]
 [ 4  5  8  9 10]
 [ 1  1  2  4  6]]


# Arithmetic operations and Broadcasting

# 38. Arithmetic operations

In [55]:
# We create two rank 1 ndarrays
x = np.array([1,2,3,4])
y = np.array([5.5,6.5,7.5,8.5])

# We print x
print('x = ', x)
print()

# We print y
print('y = ', y)
print()

# We perfrom basic element-wise operations using arithmetic symbols and functions
print('x + y =\t\t', x + y)
print('add(x,y) =\t', np.add(x,y))
print()
print('x - y =\t\t', x - y)
print('subtract(x,y) =\t', np.subtract(x,y))
print()
print('x * y =\t\t', x * y)
print('multiply(x,y) =\t', np.multiply(x,y))
print()
print('x / y =\t\t', x / y)
print('divide(x,y) =\t', np.divide(x,y))

x =  [1 2 3 4]

y =  [5.5 6.5 7.5 8.5]

x + y =		 [ 6.5  8.5 10.5 12.5]
add(x,y) =	 [ 6.5  8.5 10.5 12.5]

x - y =		 [-4.5 -4.5 -4.5 -4.5]
subtract(x,y) =	 [-4.5 -4.5 -4.5 -4.5]

x * y =		 [ 5.5 13.  22.5 34. ]
multiply(x,y) =	 [ 5.5 13.  22.5 34. ]

x / y =		 [0.18181818 0.30769231 0.4        0.47058824]
divide(x,y) =	 [0.18181818 0.30769231 0.4        0.47058824]


# 39. Arithmetic operations on 2D arrays

In [56]:
# We create two rank 2 ndarrays
X = np.array([1,2,3,4]).reshape(2,2)
Y = np.array([5.5,6.5,7.5,8.5]).reshape(2,2)

# We print X
print('X = \n', X)
print()

# We print Y
print('Y = \n', Y)
print()

# We perform basic element-wise operations using arithmetic symbols and functions
print('X + Y = \n', X + Y)
print()
print('add(X,Y) = \n', np.add(X,Y))
print()
print('X - Y = \n', X - Y)
print()
print('subtract(X,Y) = \n', np.subtract(X,Y))
print()
print('X * Y = \n', X * Y)
print()
print('multiply(X,Y) = \n', np.multiply(X,Y))
print()
print('X / Y = \n', X / Y)
print()
print('divide(X,Y) = \n', np.divide(X,Y))

X = 
 [[1 2]
 [3 4]]

Y = 
 [[5.5 6.5]
 [7.5 8.5]]

X + Y = 
 [[ 6.5  8.5]
 [10.5 12.5]]

add(X,Y) = 
 [[ 6.5  8.5]
 [10.5 12.5]]

X - Y = 
 [[-4.5 -4.5]
 [-4.5 -4.5]]

subtract(X,Y) = 
 [[-4.5 -4.5]
 [-4.5 -4.5]]

X * Y = 
 [[ 5.5 13. ]
 [22.5 34. ]]

multiply(X,Y) = 
 [[ 5.5 13. ]
 [22.5 34. ]]

X / Y = 
 [[0.18181818 0.30769231]
 [0.4        0.47058824]]

divide(X,Y) = 
 [[0.18181818 0.30769231]
 [0.4        0.47058824]]


# 40. Using sqrt, exp, power functions

In [57]:
# We create a rank 1 ndarray
x = np.array([1,2,3,4])

# We print x
print('x = ', x)
print()

# We apply different mathematical functions to all elements of x
print('EXP(x) =', np.exp(x))
print()
print('SQRT(x) =',np.sqrt(x))
print()
print('POW(x,2) =',np.power(x,2)) # We raise all elements to the power of 2

x =  [1 2 3 4]

EXP(x) = [ 2.71828183  7.3890561  20.08553692 54.59815003]

SQRT(x) = [1.         1.41421356 1.73205081 2.        ]

POW(x,2) = [ 1  4  9 16]


# 41. Using mean, sum, min, max, standard deviation, median

In [58]:
# We create a 2 x 2 ndarray
X = np.array([[1,2], [3,4]])

# We print x
print('X = \n', X)
print()

print('Average of all elements in X:', X.mean())
print('Average of all elements in the columns of X:', X.mean(axis=0))
print('Average of all elements in the rows of X:', X.mean(axis=1))
print()
print('Sum of all elements in X:', X.sum())
print('Sum of all elements in the columns of X:', X.sum(axis=0))
print('Sum of all elements in the rows of X:', X.sum(axis=1))
print()
print('Standard Deviation of all elements in X:', X.std())
print('Standard Deviation of all elements in the columns of X:', X.std(axis=0))
print('Standard Deviation of all elements in the rows of X:', X.std(axis=1))
print()
print('Median of all elements in X:', np.median(X))
print('Median of all elements in the columns of X:', np.median(X,axis=0))
print('Median of all elements in the rows of X:', np.median(X,axis=1))
print()
print('Maximum value of all elements in X:', X.max())
print('Maximum value of all elements in the columns of X:', X.max(axis=0))
print('Maximum value of all elements in the rows of X:', X.max(axis=1))
print()
print('Minimum value of all elements in X:', X.min())
print('Minimum value of all elements in the columns of X:', X.min(axis=0))
print('Minimum value of all elements in the rows of X:', X.min(axis=1))

X = 
 [[1 2]
 [3 4]]

Average of all elements in X: 2.5
Average of all elements in the columns of X: [2. 3.]
Average of all elements in the rows of X: [1.5 3.5]

Sum of all elements in X: 10
Sum of all elements in the columns of X: [4 6]
Sum of all elements in the rows of X: [3 7]

Standard Deviation of all elements in X: 1.118033988749895
Standard Deviation of all elements in the columns of X: [1. 1.]
Standard Deviation of all elements in the rows of X: [0.5 0.5]

Median of all elements in X: 2.5
Median of all elements in the columns of X: [2. 3.]
Median of all elements in the rows of X: [1.5 3.5]

Maximum value of all elements in X: 4
Maximum value of all elements in the columns of X: [3 4]
Maximum value of all elements in the rows of X: [2 4]

Minimum value of all elements in X: 1
Minimum value of all elements in the columns of X: [1 2]
Minimum value of all elements in the rows of X: [1 3]


# 42. Add single numbers to all the elements of 2D array

In [59]:
# We create a 2 x 2 ndarray
X = np.array([[1,2], [3,4]])

# We print x
print('X = \n', X)
print()

print('3 * X = \n', 3 * X)
print()
print('3 + X = \n', 3 + X)
print()
print('X - 3 = \n', X - 3)
print()
print('X / 3 = \n', X / 3)

X = 
 [[1 2]
 [3 4]]

3 * X = 
 [[ 3  6]
 [ 9 12]]

3 + X = 
 [[4 5]
 [6 7]]

X - 3 = 
 [[-2 -1]
 [ 0  1]]

X / 3 = 
 [[0.33333333 0.66666667]
 [1.         1.33333333]]


# 43. Broadcasting

In [60]:
# We create a rank 1 ndarray
x = np.array([1,2,3])

# We create a 3 x 3 ndarray
Y = np.array([[1,2,3],[4,5,6],[7,8,9]])

# We create a 3 x 1 ndarray
Z = np.array([1,2,3]).reshape(3,1)

# We print x
print('x = ', x)
print()

# We print Y
print('Y = \n', Y)
print()

# We print Z
print('Z = \n', Z)
print()

print('x + Y = \n', x + Y)
print()
print('Z + Y = \n',Z + Y)

x =  [1 2 3]

Y = 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

Z = 
 [[1]
 [2]
 [3]]

x + Y = 
 [[ 2  4  6]
 [ 5  7  9]
 [ 8 10 12]]

Z + Y = 
 [[ 2  3  4]
 [ 6  7  8]
 [10 11 12]]
